name: Schema

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  schema:
    name: Check schema
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: thiagodnf/yaml-schema-checker@v0.0.8
        with:
          jsonSchemaFile: spaces.schema.json
          yamlFiles: spaces.yml
